// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6F1y1ZF5thRt-XU26nf3FQQniPL-C6b8',
    appId: '1:928820459789:web:b25604cf958c0833a49844',
    messagingSenderId: '928820459789',
    projectId: 'flutter-mob-notes-app',
    authDomain: 'flutter-mob-notes-app.firebaseapp.com',
    storageBucket: 'flutter-mob-notes-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSVkfwrJV3AjOLbxoG1wIGPwVO7BvZ-hQ',
    appId: '1:928820459789:android:b96576dab765ad93a49844',
    messagingSenderId: '928820459789',
    projectId: 'flutter-mob-notes-app',
    storageBucket: 'flutter-mob-notes-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPshVj0MxShrJADgUhg64z0tsi1r4J0lU',
    appId: '1:928820459789:ios:c00fafdc6d65efeea49844',
    messagingSenderId: '928820459789',
    projectId: 'flutter-mob-notes-app',
    storageBucket: 'flutter-mob-notes-app.appspot.com',
    iosClientId: '928820459789-jo3jknlfbm134u7prmabu061ci8lc1vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPshVj0MxShrJADgUhg64z0tsi1r4J0lU',
    appId: '1:928820459789:ios:c00fafdc6d65efeea49844',
    messagingSenderId: '928820459789',
    projectId: 'flutter-mob-notes-app',
    storageBucket: 'flutter-mob-notes-app.appspot.com',
    iosClientId: '928820459789-jo3jknlfbm134u7prmabu061ci8lc1vl.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobNotes',
  );
}
